/** Japanese interface labels. */
export const labels = {
  'site.skipToContent': '本文へ移動',
  'nav.home': 'ホーム',
  'nav.posts': '記事',
  'nav.tags': 'タグ',
  'nav.categories': 'カテゴリ',
  'nav.archives': 'アーカイブ',
  'nav.about': 'このブログについて',
  'nav.toggleMenu': 'メニューを開閉',
  'theme.toggle': 'テーマを切り替え',
  'theme.light': 'ライト',
  'theme.dark': 'ダーク',
  'theme.system': 'システム設定',
  'post.publishedOn': '公開日',
  'post.updatedOn': '更新日',
  'post.toc': '目次',
  'post.tags': 'タグ',
  'post.categories': 'カテゴリ',
  'post.previous': '前の記事',
  'post.next': '次の記事',
  'post.comments': 'コメント',
  'post.commentsDisabled': 'この記事のコメントは無効です。',
  'post.commentsSetupTitle': 'コメントの設定が必要です',
  'post.commentsSetupBody': 'Giscusを利用するには、リポジトリ情報を設定してください。',
  'post.commentsSetupStep1':
    '`giscus.app`で、Discussionsを有効にした公開GitHubリポジトリを選択します。',
  'post.commentsSetupStep2':
    '生成された`data-repo-id`、`data-category`、`data-category-id`をコピーします。',
  'post.commentsSetupStep3':
    '`.env`に`PUBLIC_GISCUS_ENABLED`、`PUBLIC_GISCUS_REPO`、`PUBLIC_GISCUS_REPO_ID`、`PUBLIC_GISCUS_CATEGORY`、`PUBLIC_GISCUS_CATEGORY_ID`を設定します。',
  'post.commentsSetupStep4': 'サイトを再ビルドするとコメント欄が表示されます。',
  'post.commentsSetupDocs': 'giscus.appを開く',
  'post.share': '共有',
  'post.copyLink': 'リンクをコピー',
  'post.copied': 'コピーしました',
  'post.author': '著者',
  'list.allPosts': 'すべての記事',
  'list.empty': '記事がありません。',
  'list.tagPosts': 'このタグの記事',
  'list.categoryPosts': 'このカテゴリの記事',
  'list.totalPosts': '件',
  'list.totalPostsOne': '件',
  'pagination.previous': '前のページ',
  'pagination.next': '次のページ',
  'pagination.page': 'ページ',
  'pagination.of': '/',
  'archives.title': 'アーカイブ',
  'archives.empty': '記事はまだありません。',
  'tags.title': 'タグ',
  'tags.empty': 'タグはまだありません。',
  'categories.title': 'カテゴリ',
  'categories.empty': 'カテゴリはまだありません。',
  'code.copy': 'コピー',
  'code.copied': 'コピーしました',
  '404.title': 'ページが見つかりません',
  '404.description': 'お探しのページは見つかりませんでした。',
  '404.cta': 'ホームに戻る',
  'footer.poweredBy': 'Powered by',
  'footer.theme': 'theme',
  'footer.copyright': 'All rights reserved.',
} as const;

export type UIKey = keyof typeof labels;
